### ISSUE TITLE
Tagvelden disabelen

### ISSUE THREAD

**Issue by Swendude** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#259]

**Comment by copebo** [comment]
**Acceptatiecriteria**
- [ ] De muteerpagina van een verordeningsartikel heeft geen tagveld meer
- [ ] De muteerpagina van een beleidsbeslissing heeft geen tagveld meer
- [ ] De muteerpagina van een maatregel heeft geen tagveld meer
- [ ] De muteerpagina van een ambitie heeft geen tagveld meer
- [ ] De muteerpagina van een opgave heeft geen tagveld meer
- [ ] De muteerpagina van een beleidsregel heeft geen tagveld meer
