### ISSUE TITLE
⚠️ Is de import van de data uit Mendix goed gegaan? Zie omschrijving

### ISSUE THREAD

**Issue by Swendude** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#3]
Zodra je de maatregel "Gebiedsdossiers waarin de situatie rond drinkwater in kaart wordt gebracht en actueel wordt gehouden" bekijkt. Staat er in Mendix minder tekst dan in onze eigen omgeving.

Het gaat om het omschrijving veld: https://test.obzh.nl/muteer/maatregelen/edit/868

In Mendix te vinden door te zoeken naar de BB "Drinkwater", dan bij het tabje "Relaties en koppelingen", onder het kopje programma's.

**Comment by copebo** [comment]
Is opgelost. Data kwam vanuit Mendix Acc en niet uit Mendix Prod
