### ISSUE TITLE
Change website link in repository About

### ISSUE THREAD

**Issue by Ainali** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#547]
Right now it links to https://zuid-holland.nl/ but perhaps a better link would be https://omgevingsbeleid.zuid-holland.nl/ as it is the beta site (if I understand it correctly)? 

This would make it easier for people to take a look at what the codebase is about and see what the frontend looks like.

**Comment by Aidenbuis** [comment]
Hey Jan,

Sorry for the late response, but yes that is definitely a good improvement!
I've changed it :-)
