### ISSUE TITLE
⚠️ EERST LEZEN VOOR HET TESTEN: Instructies over wat getest kan worden

### ISSUE THREAD

**Issue by Swendude** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#67]
Het systeem is continue aan het wijzigen, daarom sommen wij hieronder de onderwerpen op die getest kunnen worden:

*  Beleidsbeslissingen
*  Beleidsrelaties
*  Meldingen

**Comment by copebo** [comment]
Niet relevant. Kan als een note worden geplaatst in Github
