### ISSUE TITLE
Typo in publiccode.yml : License name

### ISSUE THREAD

**Issue by ericherman** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#738]
**Taken**
- [ ] fix license name

**Comment by Ainali** [comment]
When running the file in the validation at https://publiccode-editor.developers.italia.it/# the following error is produced: 

`{"status":422,"message":"Validation Errors","validationErrors":[{"Key":"legal/license","Reason":"invalid value UPL-1.2 License: invalid license \"UPL-1.2\" at 0 (\"UPL-1\")"}]}`
