### ISSUE TITLE
Ambitie - Toevoegen nieuwe: Datum issue

### ISSUE THREAD

**Issue by Swendude** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#77]
Zodra je een nieuwe ambitie toevoegt, dan krijg je de melding dat de inwerkingtreding verplicht is, terwijl het om de uitwerkingtreding gaat.

![image](/uploads/8bffcb9c7cd8594e0a704ed72c2deb5e/image.png)

Zodra je hier aan wilt werken (nieuwe uittredingsdatum) dan wordt de inwerkingtreding 'invalid'

Opslaan is ook niet mogelijk...

Opmaak van datumvelden (lengte is anders)

**Comment by copebo** [comment]
Ziet er uit alsof het geregeld is.
