### ISSUE TITLE
Possible unintentional text loss in merge

### ISSUE THREAD

**Issue by ericherman** [Provincie-Zuid-Holland/Omgevingsbeleid-Frontend#817]
Looking at merge [8ee8a7b](https://github.com/Provincie-Zuid-Holland/Omgevingsbeleid-Frontend/commit/8ee8a7b4f676f126d71d5accee45ca22be816d7f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L14-L19) it looks like the section on the Standard for Public Code was removed.

If that was not intentional, you may wish to add it back.

See also: c28183d69fcc30160bb08d98ca62a6bf7cc08a9e

**Comment by Stefwint** [comment]
@ericherman This was not intentional indeed. I just opened a PR to put it back:
https://github.com/Provincie-Zuid-Holland/Omgevingsbeleid-Frontend/pull/818
